spring:
  datasource:
    username: admin
    password: test123
app.client:
  app2:
    datasource:
      driverClassName: oracle.jdbc.OracleDriver
      username: xxxxx
      password: dbpwd
      validationQuery: "SELECT 1 FROM dual"